// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using DataAccess.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace DataAccess.Models
{
    public partial interface IPractice4_ProductsContextProcedures
    {
        Task<int> Create_ProductAsync(string product_name, DateOnly? date, int? p_id, int? p_price, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> CreateProductAsync(string product_name, DateOnly? date, int? p_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeleteProductAsync(int? p_id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<ReadProductsResult>> ReadProductsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> Update_ProductAsync(int? p_id, string p_name, DateOnly? p_date, int? p_price, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdateProductAsync(int? p_id, string p_name, DateOnly? p_date, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
