// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DataAccess.Models;

public partial class Practice4_ProductsContext : DbContext
{
    public Practice4_ProductsContext(DbContextOptions<Practice4_ProductsContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Purchase> Purchases { get; set; }

    public virtual DbSet<Sale> Sales { get; set; }

    public virtual DbSet<SoldAndPurchasedProduct> SoldAndPurchasedProducts { get; set; }

    public virtual DbSet<WeeklyProductStat> WeeklyProductStats { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__47027DF5E54CF06C");

            entity.Property(e => e.ProductId)
                .ValueGeneratedNever()
                .HasColumnName("product_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.ProductName)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("product_name");
        });

        modelBuilder.Entity<Purchase>(entity =>
        {
            entity.HasKey(e => e.PurchaseId).HasName("PK__Purchase__87071CB9B204ECF4");

            entity.Property(e => e.PurchaseId)
                .ValueGeneratedNever()
                .HasColumnName("purchase_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.ProductName)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("product_name");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.Product).WithMany(p => p.Purchases)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Purchases__produ__3C69FB99");
        });

        modelBuilder.Entity<Sale>(entity =>
        {
            entity.HasKey(e => e.SaleId).HasName("PK__Sales__E1EB00B26C627EF4");

            entity.Property(e => e.SaleId)
                .ValueGeneratedNever()
                .HasColumnName("sale_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.ProductId).HasColumnName("product_id");
            entity.Property(e => e.ProductName)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("product_name");
            entity.Property(e => e.Quantity).HasColumnName("quantity");

            entity.HasOne(d => d.Product).WithMany(p => p.Sales)
                .HasForeignKey(d => d.ProductId)
                .HasConstraintName("FK__Sales__product_i__398D8EEE");
        });

        modelBuilder.Entity<SoldAndPurchasedProduct>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("SoldAndPurchasedProducts");

            entity.Property(e => e.ProductName)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("product_name");
        });

        modelBuilder.Entity<WeeklyProductStat>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("WeeklyProductStats");

            entity.Property(e => e.ProductName)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("product_name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}