// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccess.Models
{
    public partial class ReadProductsResult
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public DateOnly? date { get; set; }
        public int? Price { get; set; }
    }
}
