// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class Sale
{
    public int SaleId { get; set; }

    public int? ProductId { get; set; }

    public string ProductName { get; set; }

    public int? Quantity { get; set; }

    public DateOnly? Date { get; set; }

    public virtual Product Product { get; set; }
}