// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class SoldAndPurchasedProduct
{
    public string ProductName { get; set; }

    public int? SoldQuantity { get; set; }

    public int? PurchasedQuantity { get; set; }
}