// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DataAccess.Models;

public partial class WeeklyProductStat
{
    public string ProductName { get; set; }

    public int? AverageSold { get; set; }

    public int? MostExpensive { get; set; }

    public int? Cheapest { get; set; }
}