// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    [Migration("20240912233441_AddingDataToProductList")]
    partial class AddingDataToProductList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Totis",
                            Price = 15
                        },
                        new
                        {
                            Id = 102,
                            Name = "Cheetos",
                            Price = 23
                        },
                        new
                        {
                            Id = 103,
                            Name = "Doritos",
                            Price = 20
                        },
                        new
                        {
                            Id = 104,
                            Name = "Sabritones",
                            Price = 30
                        },
                        new
                        {
                            Id = 105,
                            Name = "Arizona",
                            Price = 14
                        },
                        new
                        {
                            Id = 106,
                            Name = "Chokis",
                            Price = 20
                        },
                        new
                        {
                            Id = 107,
                            Name = "Emperador",
                            Price = 21
                        },
                        new
                        {
                            Id = 108,
                            Name = "Boing",
                            Price = 16
                        },
                        new
                        {
                            Id = 109,
                            Name = "Takis",
                            Price = 19
                        },
                        new
                        {
                            Id = 110,
                            Name = "Oreo",
                            Price = 25
                        });
                });

            modelBuilder.Entity("Model.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
