// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AplicationDBContext))]
    partial class AplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Models.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventory");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Totis",
                            Price = 15,
                            Quantity = 900
                        },
                        new
                        {
                            Id = 102,
                            Name = "Cheetos",
                            Price = 23,
                            Quantity = 800
                        },
                        new
                        {
                            Id = 103,
                            Name = "Doritos",
                            Price = 20,
                            Quantity = 860
                        },
                        new
                        {
                            Id = 104,
                            Name = "Sabritones",
                            Price = 30,
                            Quantity = 970
                        },
                        new
                        {
                            Id = 105,
                            Name = "Arizona",
                            Price = 14,
                            Quantity = 750
                        },
                        new
                        {
                            Id = 106,
                            Name = "Chokis",
                            Price = 20,
                            Quantity = 870
                        },
                        new
                        {
                            Id = 107,
                            Name = "Emperador",
                            Price = 21,
                            Quantity = 790
                        },
                        new
                        {
                            Id = 108,
                            Name = "Boing",
                            Price = 16,
                            Quantity = 940
                        },
                        new
                        {
                            Id = 109,
                            Name = "Takis",
                            Price = 19,
                            Quantity = 780
                        },
                        new
                        {
                            Id = 110,
                            Name = "Oreo",
                            Price = 25,
                            Quantity = 890
                        });
                });

            modelBuilder.Entity("Model.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Name = "Totis",
                            Price = 15
                        },
                        new
                        {
                            Id = 102,
                            Name = "Cheetos",
                            Price = 23
                        },
                        new
                        {
                            Id = 103,
                            Name = "Doritos",
                            Price = 20
                        },
                        new
                        {
                            Id = 104,
                            Name = "Sabritones",
                            Price = 30
                        },
                        new
                        {
                            Id = 105,
                            Name = "Arizona",
                            Price = 14
                        },
                        new
                        {
                            Id = 106,
                            Name = "Chokis",
                            Price = 20
                        },
                        new
                        {
                            Id = 107,
                            Name = "Emperador",
                            Price = 21
                        },
                        new
                        {
                            Id = 108,
                            Name = "Boing",
                            Price = 16
                        },
                        new
                        {
                            Id = 109,
                            Name = "Takis",
                            Price = 19
                        },
                        new
                        {
                            Id = 110,
                            Name = "Oreo",
                            Price = 25
                        });
                });

            modelBuilder.Entity("Model.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("PurchaseId");

                    b.ToTable("Purchase");

                    b.HasData(
                        new
                        {
                            PurchaseId = 301,
                            Name = "Arizona",
                            Quantity = 400
                        },
                        new
                        {
                            PurchaseId = 302,
                            Name = "Cheetos",
                            Quantity = 500
                        },
                        new
                        {
                            PurchaseId = 303,
                            Name = "Sabritones",
                            Quantity = 200
                        },
                        new
                        {
                            PurchaseId = 304,
                            Name = "Boing",
                            Quantity = 400
                        },
                        new
                        {
                            PurchaseId = 305,
                            Name = "Chokis",
                            Quantity = 300
                        },
                        new
                        {
                            PurchaseId = 306,
                            Name = "Sabritones",
                            Quantity = 500
                        },
                        new
                        {
                            PurchaseId = 307,
                            Name = "Chokis",
                            Quantity = 450
                        },
                        new
                        {
                            PurchaseId = 308,
                            Name = "Totis",
                            Quantity = 300
                        },
                        new
                        {
                            PurchaseId = 309,
                            Name = "Cheetos",
                            Quantity = 250
                        },
                        new
                        {
                            PurchaseId = 310,
                            Name = "Totis",
                            Quantity = 350
                        });
                });

            modelBuilder.Entity("Model.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 201,
                            Name = "Boing",
                            Quantity = 100
                        },
                        new
                        {
                            SaleId = 202,
                            Name = "Oreo",
                            Quantity = 230
                        },
                        new
                        {
                            SaleId = 203,
                            Name = "Totis",
                            Quantity = 210
                        },
                        new
                        {
                            SaleId = 204,
                            Name = "Arizona",
                            Quantity = 140
                        },
                        new
                        {
                            SaleId = 205,
                            Name = "Oreo",
                            Quantity = 180
                        },
                        new
                        {
                            SaleId = 206,
                            Name = "Arizona",
                            Quantity = 258
                        },
                        new
                        {
                            SaleId = 207,
                            Name = "Totis",
                            Quantity = 305
                        },
                        new
                        {
                            SaleId = 208,
                            Name = "Boing",
                            Quantity = 179
                        },
                        new
                        {
                            SaleId = 209,
                            Name = "Totis",
                            Quantity = 250
                        },
                        new
                        {
                            SaleId = 210,
                            Name = "Cheetos",
                            Quantity = 289
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
